#! /bin/bash
# If the battery level is under 20 percent, this script will run.

# Choose display to output error message to
export DISPLAY=:0
# Play warning sound
play /usr/share/sounds/Oxygen-Sys-App-Error-Critical.ogg > /dev/null 2>&1 &
# Show popup message, meant for KDE Plasma.
kdialog --passivepopup "The battery is too low to begin backup. Charge remaining: $battlevel% Will attempt again in 5 minutes." "5"
