#! /bin/bash
# Runs when the Rsync finishes.

# Select display for message.
export DISPLAY=:0
# Show popup for 3 seconds when Rsync finishes. Meant for KDE Plasma.
kdialog --passivepopup "Rsync complete." "3"
